apiVersion: v1
kind: Config
clusters:
- name: "rke2-cluster1"
  cluster:
    server: "https://rancher.20.219.24.217.sslip.io/k8s/clusters/c-m-8lkbnk9k"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJwekNDQ\
      VUyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQTdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRXdIa\
      GNOTWpJdwpNekUxTURrd01ESTFXaGNOTXpJd016RXlNRGt3TURJMVdqQTdNUnd3R2dZRFZRUUtFe\
      E5rZVc1aGJXbGpiR2x6CmRHVnVaWEl0YjNKbk1Sc3dHUVlEVlFRREV4SmtlVzVoYldsamJHbHpkR\
      1Z1WlhJdFkyRXdXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNydlZPTm50YWlQM\
      jl6MklQRFIvZzJ5QUJ6cVRBajc0bER6elpCQnhWKwpQaVdXaDgyalRMTmlnbGVrN2xZcGVxclNyR\
      FM1WkdURVpmQmFpOGc5em1zdm8wSXdRREFPQmdOVkhROEJBZjhFCkJBTUNBcVF3RHdZRFZSMFRBU\
      UgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVYXVBMHZmNFlWQXhMd214MHl2cnIKTDVUQllOY3dDZ\
      1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBSzF3YWpHMWhvNWpHZ0RRQldpeEp2U3FJaFQyVWF3dwo4Z\
      UYvNnJZM1VxdE9BaUJHZ3drVGg3OGlLSjEwdmg4ZFVzK2pCY3UrdmQ0T0ZsY3N1dmNkbTk2bGZRP\
      T0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ=="

users:
- name: "rke2-cluster1"
  user:
    token: "kubeconfig-user-n4hfgngx76:v9jtnqxq8dnpmfj2784wvdb6s4qcbpx6pk2zq2kdrxqr8fdvb626pw"


contexts:
- name: "rke2-cluster1"
  context:
    user: "rke2-cluster1"
    cluster: "rke2-cluster1"

current-context: "rke2-cluster1"
