registry: docker.io
tag: ${neuvector_version}
manager:
  image:
    repository: "neuvector/manager"
  ingress:
    enabled: true
    host: ${ingress_host}
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    tls: true
    secretName: "neuvector-tls"
controller:
  image:
    repository: "neuvector/controller"
enforcer:
  image:
    repository: "neuvector/enforcer"
cve:
  scanner:
    image:
      repository: "neuvector/scanner"
  updater:
    image:
      repository: "neuvector/updater"
k3s:
  enabled: true
